'use client';
import Link from 'next/link';
import { ArrowLeft, Sparkles, Check, X } from 'lucide-react';
import { Card } from '@/components/ui/Card';

export default function AiLinkingAssistant() {
  const suggestions = [
    {
      source: 'MERN Architecture Guide',
      target: 'Nexus SaaS Boilerplate',
      anchor: 'enterprise SaaS boilerplate',
      placement: 'Inline within paragraph 3',
      rationale: 'Connects the theoretical architecture to your practical product implementation.',
      confidence: 95
    },
    {
      source: 'React Performance Tips',
      target: 'React Development Services',
      anchor: 'expert React consulting',
      placement: 'Conclusion section CTA',
      rationale: 'High purchase intent topic leading to service offering.',
      confidence: 88
    }
  ];

  return (
    <div className="p-8 max-w-7xl mx-auto space-y-8">
      <div className="flex justify-between items-center">
        <div>
          <h1 className="text-3xl font-black text-white tracking-tight flex items-center gap-2">
            <Sparkles className="text-indigo-400" /> AI Internal Link Assistant
          </h1>
          <p className="text-gray-400 mt-2">Approve or reject contextually relevant internal links generated by the AI.</p>
        </div>
        <Link href="/admin/dashboard/seo/linking" className="px-4 py-2 bg-gray-800 hover:bg-gray-700 text-sm font-semibold rounded-lg text-white flex items-center gap-2">
          <ArrowLeft size={16} /> Back
        </Link>
      </div>

      <div className="space-y-4">
        {suggestions.map((s, i) => (
          <Card key={i} className="bg-gray-900 border-gray-800 p-6 flex flex-col md:flex-row gap-6 justify-between items-start md:items-center">
            <div className="flex-1 space-y-2">
              <div className="flex items-center gap-2 text-sm text-gray-400 mb-2">
                <span>{s.source}</span>
                <span>→</span>
                <span className="text-white font-semibold">{s.target}</span>
              </div>
              
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <div className="text-xs text-gray-500 uppercase tracking-wider mb-1">Suggested Anchor</div>
                  <div className="text-emerald-400 font-mono text-sm bg-gray-800 px-2 py-1 rounded inline-block">
                    {s.anchor}
                  </div>
                </div>
                <div>
                  <div className="text-xs text-gray-500 uppercase tracking-wider mb-1">Placement</div>
                  <div className="text-gray-300 text-sm">{s.placement}</div>
                </div>
              </div>
              
              <div className="mt-4 pt-4 border-t border-gray-800">
                <div className="text-xs text-gray-500 uppercase tracking-wider mb-1">AI Rationale</div>
                <p className="text-sm text-gray-400 italic">{s.rationale}</p>
              </div>
            </div>
            
            <div className="flex flex-col items-center gap-4 border-l border-gray-800 pl-6 w-full md:w-auto">
              <div className="text-center">
                <div className="text-2xl font-black text-indigo-400">{s.confidence}%</div>
                <div className="text-xs text-gray-500">Confidence</div>
              </div>
              <div className="flex gap-2 w-full">
                <button className="flex-1 md:flex-none p-2 bg-emerald-500/10 hover:bg-emerald-500/20 text-emerald-500 rounded transition-colors" title="Approve">
                  <Check size={20} className="mx-auto" />
                </button>
                <button className="flex-1 md:flex-none p-2 bg-red-500/10 hover:bg-red-500/20 text-red-500 rounded transition-colors" title="Reject">
                  <X size={20} className="mx-auto" />
                </button>
              </div>
            </div>
          </Card>
        ))}
      </div>
    </div>
  );
}
